services:
  congressmcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: congressmcp_service
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./secrets.ini:/app/secrets.ini
    working_dir: /app/congressMCP
    command: sleep infinity



    